experiencein/experiencein/urls.py
"""from django.contrib import admin
from django.urls import path
from perfis import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
]"""

from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('perfis.urls')),
    path('', include('usuarios.urls'))
]

experiencein/perfis/urls.py
from django.urls import path, re_path, include
from perfis import views
from rest_framework.authtoken import views as auth_views

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('perfis', views.PerfilViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('perfil/', views.get_meu_perfil, name='perfil'),
    path('convites/', views.get_convites, name='convites'),
    path('convites/convidar/<int:perfil_id>', views.convidar, name='convidar'),
    path('convites/aceitar/<int:convite_id>', views.aceitar, name='aceitar'),
    path('login/', auth_views.obtain_auth_token, name='login')
]

experiencein/usuarios/urls.py
from django.urls import path
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('registrar/', RegistrarUsuarioView.as_view(), name='registrar'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', LogoutView.as_view(), name='logout')
]

experiencein/perfis/models.py
from pyclbr import Class
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Perfil(models.Model):

    nome = models.CharField(max_length=255, null=False)
    # sem email
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)

    contatos = models.ManyToManyField('self')
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="perfil")

    @property
    def email(self):
        return self.usuario.email

    def convidar(self, perfil_convidado):
        Convite(solicitante=self, convidado=perfil_convidado).save()

class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)
        self.delete()

experiencein/usuarios/models.py
from django.db import models

# Create your models here.

experiencein/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):

    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        user_exists = User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro('Usuario ja existente')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

experiencein/perfis/views.py
# editando o arquivo experiencein/perfis/views.py
from ast import If
from django.shortcuts import render
from django.http import HttpResponse
from perfis.models import Perfil, Convite
# importando redirect
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseForbidden

from rest_framework import viewsets, response, status, exceptions
from rest_framework.decorators import api_view, renderer_classes
from rest_framework.renderers import JSONRenderer, BrowsableAPIRenderer
from rest_framework.permissions import AllowAny

from .serializers import PerfilSerializer, PerfilSimplificadoSerializer, ConviteSerializer

class PerfilViewSet(viewsets.ModelViewSet):
    queryset = Perfil.objects.all()
    serializer_class = PerfilSerializer

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return PerfilSimplificadoSerializer
        return super().get_serializer_class()

    def get_permissions(self):
        if self.request.method == 'POST':
            return (AllowAny(),)
        return super().get_permissions()

@api_view(['GET'])
@renderer_classes((JSONRenderer, BrowsableAPIRenderer))
def get_convites(request, *args, **kwargs):
    perfil_logado = get_perfil_logado(request)
    convites = Convite.objects.filter(convidado=perfil_logado)
    serializer = ConviteSerializer(convites, many=True)
    return response.Response(serializer.data, status=status.HTTP_200_OK)

@api_view(['POST'])
@renderer_classes((JSONRenderer, BrowsableAPIRenderer))
def convidar(request, *args, **kwargs):
    try: 
        perfil_a_convidar = Perfil.objects.get(id=kwargs['perfil_id'])
    except:
        raise exceptions.NotFound('Não foi encontrado um perfil com o id informado.')
    perfil_logado = get_perfil_logado(request)
    if perfil_a_convidar != perfil_logado:
        perfil_logado.convidar(perfil_a_convidar)
        return response.Response({
            'mensagem': f'Convite enviado com sucesso para {perfil_a_convidar.email}'},
            status=status.HTTP_201_CREATED)
    raise exceptions.ParseError('Você não pode convidar o perfil com o id informado.')

@api_view(['POST'])
@renderer_classes((JSONRenderer, BrowsableAPIRenderer))
def aceitar(request, *args, **kwargs):
    perfil_logado = get_perfil_logado(request)
    try:
        convite = Convite.objects.filter(convidado=perfil_logado).get(id=kwargs['convite_id'])
    except:
        raise exceptions.NotFound('Não foi encontrado um convite com o id informado')
    convite.aceitar()
    return response.Response({
        'mensagem': 'Convite aceito com sucesso.'},
        status=status.HTTP_201_CREATED)

@api_view(['GET'])
@renderer_classes((JSONRenderer, BrowsableAPIRenderer))
def get_meu_perfil(request, *args, **kwargs):
    perfil_logado = get_perfil_logado(request)
    serializer = PerfilSerializer(perfil_logado)
    return response.Response(serializer.data, status=status.HTTP_200_OK)

def get_perfil_logado(request):
    return request.user.perfil

experiencein/usuarios/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.base import View
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm

class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):

        #preenche o from
        form = RegistrarUsuarioForm(request.POST)

        #verifica se eh valido
        if form.is_valid():

            dados_form = form.data

            #cria o usuario
            usuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])            

            #cria o perfil
            perfil = Perfil(nome=dados_form['nome'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)

            #grava no banco
            perfil.save()

            #redireciona para index
            return redirect('index')

        #so chega aqui se nao for valido
        #vamos devolver o form para mostrar o formulario preenchido 
        return render(request, self.template_name, {'form' : form})

experiencein/perfis/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/main.css" %}" rel="stylesheet">
        <title>ExperienceIn</title>
    </head>
    <body>
            <div class="container">
            <div class="header">
                <ul class="nav nav-pills pull-right">
                    <li class=""><a href="{% url 'index' %}">{{perfil_logado.nome}}</a></li>
                    <li class=""><a href="/logout/">Logout</a></li>
                </ul>
                <h3 class="text-muted">ExperienceIn</h3>
            </div>

            <div class="row content">
                {% block body %}
                {% endblock %}            
            </div>
        </div>
    </body>
</html>

experiencein/perfis/templates/index.html
<!-- experiencein/perfis/templates/index.html --> 

{% extends "base.html" %}

{% block body %}
<div class="col-lg-12">

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Todos os Perfis</strong>
        </div>
        {% if perfis %}
            <ul>
                {% for perfil in perfis %}
                    <li>
                        <a href="{% url 'exibir' perfil.id %}">{{ perfil.nome }} / {{ perfil.email }}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Nenhum Perfil encontrado.</p>
        {% endif %}
    </div>

    <div class="panel panel-default">
        {% with total_de_convites=perfil_logado.convites_recebidos.count %}
            {% if total_de_convites %}
                <div class="panel-heading">
                    <strong>Você tem {{ total_de_convites }} convite{{ total_de_convites|pluralize }} aguardando aprovação</strong>
                </div>
                <ul class="list-group">
                    {% for convite in perfil_logado.convites_recebidos.all %}
                        <li class="list-group-item">
                                {{ convite.solicitante.nome }} 
                                <a href="{% url 'aceitar' convite.id %}" class="pull-right">aceitar</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    <p>Nenhum convite recebido :(</p>
                </div>
            {% endif %}
        {% endwith %}
    </div>

    <div class="panel panel-default">
        {% with total_de_contatos=perfil_logado.contatos.count %}
            {% if total_de_contatos %}
                <div class="panel-heading">
                        <strong>Você tem {{total_de_contatos}} contato{{ total_de_contatos|pluralize }}</strong>
                </div>
                <ul class="list-group">
                    {% for contato in perfil_logado.contatos.all %}
                        <a href="{% url 'exibir' contato.id %}" class="list-group-item">{{ contato.nome }}</a>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    <p>Você não possui contatos no momento :(</p>
                </div>
            {% endif %}
        {% endwith %}
      </div>

</div>
{% endblock %}

experiencein/perfis/templates/perfil.html
<!-- experiencein/perfis/templates/perfil.html -->

{% extends "base.html" %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h2 style="margin-top:0">{{perfil.nome}}</h2>
            <address>
                <strong>{{perfil.nome_empresa}}</strong><br>
                <abbr title="Telefone">Tel:</abbr> {{perfil.telefone}}<br>
                <a href="mailto:{{perfil.email}}">{{perfil.email}}</a> 
            </address>

        {% if ja_e_contato %}
            <div class="well well-sm">Vocês estão conectados!</div>
        {% else %}
            <a href="{% url 'convidar' perfil.id %}" class="btn btn-success" role="button">Convidar</a>
        {% endif %}

            </div>
        </div>
        {% endblock %}
    </body>
</html>

experiencein/usuarios/templates/base_usuario.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">

        <title>ExperienceIn</title>

        <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'styles/signin.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            {% block body %}

            {% endblock %} 
        </div>
    </body>
</html>

experiencein/usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

experiencein/usuarios/templates/registrar.html
<!-- experiencein/usuarios/templates/registrar.html -->

{% extends "base_usuario.html" %}

{% block body %}

  <form class="form-signin" action="{% url 'registrar' %}" method="post">

    {% csrf_token %}

    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="text" id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>

    <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome *" required >

    <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>

    <hr />

    <input type="text" id="id_telefone" name="telefone" class="form-control" placeholder="Telefone">

    <input type="text" id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

    <hr/>

     {% if form.errors %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{form.non_field_errors}}
        <p>'{{form.nome.value}}'</p>
      </div>
    {% endif %}

  </form>

{% endblock %}